# MUST EDIT BELOW
sitename: Thruput       #Your site title
tagline: Garbage In, Garbage Out   #You should always have a tagline
url: http://qzaidi.github.com/   #URL Please
ga: UA-566085-5 #Google Analytics ID
sitemap: W4pRGiRrfCiC6kbBYgPp11-rEAKpifXz1A71XOITnTc
# END
# CHOOSE YOUR PREFERENCE
highlighter: rouge
markdown:    maruku
permalink:   pretty
# END
exclude: LICENSE, README.markdown, Rakefile
